### ISSUE TITLE
How to lock after unlock?

### ISSUE THREAD

**Issue by djMax** [thebigredgeek/microlock#3]
How does one "get in line" to lock after any existing lock holder unlocks?

**Comment by thebigredgeek** [comment]
That is left up to the implementer, as there is no "one-size-fits-all" way to handle lock queuing or logic around "waiting in line".  Some times you want to immediately stop, some times you want to queue locking in a particular way (priority queue, etc), etc.  You can definitely extend the microlock class to add functionality like this.
